# Generated by Django 5.2.4 on 2025-08-18 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_delete_project_delete_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('stacks', models.ManyToManyField(blank=True, related_name='projects', to='projects.stack')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.CharField(choices=[('not_selected', 'Не выбрано'), ('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('devops', 'DevOps Engineer'), ('designer', 'UI/UX Designer'), ('qa', 'QA'), ('pm', 'PM')], default='not_selected', max_length=50)),
                ('grade_id', models.CharField(choices=[('not_selected', 'Не выбрано'), ('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Tech Lead'), ('architect', 'Архитектор')], default='not_selected', max_length=50)),
                ('count_needed', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.project')),
            ],
        ),
    ]
