# Generated by Django 5.2.4 on 2025-08-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='description',
        ),
    ]
