# Generated by Django 5.2.4 on 2025-07-13 16:19

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('avatar', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('github', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('resume', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('info', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
