# Generated by Django 5.2.4 on 2025-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade_id',
            field=models.CharField(choices=[('not_selected', 'Не выбрано'), ('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Tech Lead'), ('architect', 'Архитектор')], default='not_selected', max_length=20),
        ),
    ]
