# Generated by Django 5.2.4 on 2025-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.skill'),
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
